#! /bin/sh

sxhkd &

# Variables
gap=8
bar_height=29
gap_monocle=-8
focused="#f8818e"
unfocused="#051519"
export gap
export bar_height
export focused
export unfocused

bspc monitor -d I II III IV
# V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           $gap
bspc config top_padding          $(($bar_height + $gap))
bspc config bottom_padding       $gap
bspc config left_padding         $gap
bspc config right_padding        $gap

for side in top right bottom left; do bspc config ${side}_monocle_padding $gap_monocle; done
bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a mpv state=pseudo_tiled
bspc rule -a Zathura state=tiled

# Colors
bspc config focused_border_color $focused
bspc config normal_border_color  $unfocused

sleep 1s && setxkbmap -layout fr
compton &
$HOME/.config/polybar/launch.sh &
feh --bg-fill ~/Images/wallpaper/*.* &
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
sxhkd
